apiVersion: v1
kind: Namespace
metadata:
  name: spinnaker
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spinnaker-service-account
  namespace: spinnaker
---
apiVersion: v1
kind: Secret
metadata:
  name: spinnaker-service-account-token
  namespace: spinnaker
  annotations:
    kubernetes.io/service-account.name: spinnaker-service-account
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spinnaker-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - namespace: spinnaker
    kind: ServiceAccount
    name: spinnaker-service-account