apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- replicaset.yaml
- service.yaml
- ingress.yaml
- networkpolicy.yaml
- servicemonitor.yaml

patches:
- patch: |-
    - op: add
      path: /metadata/annotations
      value:
        moniker.spinnaker.io/cluster: "${ cluster_name ?: \"unknown\" }"
        moniker.spinnaker.io/stack: "${ stack_name ?: \"unknown\" }"
        strategy.spinnaker.io/max-version-history: "5"
  target:
    group: apps
    version: v1
    kind: ReplicaSet
    name: flask-app
- patch: |-
    - op: remove
      path: /spec/selector/app
    - op: copy
      from: /metadata/name
      path: /spec/selector/loadBalancer
  target:
    version: v1
    kind: Service
    name: flask-app
- patch: |-
    - op: add
      path: /spec/rules/0/host
      value: "${ cluster_name ?: \"unknown\" }.minikube"
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: flask-app